version: '3'
services:
  web:
    stdin_open: true
    build:
      context: . # copy all files in pwd
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    volumes:
      - /app/node_modules # (reference its own node_modules)
      - .:/app # (reference to local folders)
  tests:
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ['npm', 'run', 'test'] # (overwrite CMD for start up)
